# Generated by Django 4.2 on 2023-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['full_name'], 'verbose_name': 'Autorius', 'verbose_name_plural': 'Autoriai'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['book_title'], 'verbose_name': 'Knygos', 'verbose_name_plural': 'Knygos'},
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='about_author',
            field=models.TextField(blank=True, verbose_name='Apie autorių'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Šalis'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Autoriaus vardas, pavardė'),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_title',
            field=models.CharField(max_length=150, verbose_name='Knygos pavadinimas'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.CharField(max_length=50, verbose_name='Kalba'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.CharField(max_length=10, verbose_name='Puslapiai'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(max_length=50, verbose_name='Išleista (metai)'),
        ),
    ]
